Week2/ecommerce/config/routes.rb
Rails.application.routes.draw do
  root :to => "laptops#welcome"
  resources :laptops
  resources :backpacks
end

Week2/ecommerce/app/models/backpack.rb
class Backpack < ActiveRecord::Base
end

Week2/ecommerce/app/models/laptop.rb
class Laptop < ActiveRecord::Base
end

Week2/ecommerce/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Week2/ecommerce/app/controllers/backpacks_controller.rb
class BackpacksController < ApplicationController
def index
		@backpacks = Backpack.all
	end
	def new
		@backpack = Backpack.new
	end
	def show
		@backpack = Backpack.find(params[:id])
	end
	def edit
		@backpack = Backpack.find(params[:id])
	end
	def create
		@backpack = Backpack.new(backpack_params)
		@backpack.save
		redirect_to backpack_path(@backpack)
	end
	def update
		@backpack = Backpack.find(params[:id])
		@backpack.update(backpack_params)
		redirect_to backpack_path(@backpack)
	end
	def destroy
		@backpack = Backpack.find(params[:id])
		@backpack.destroy
		redirect_to backpacks_path
	end
	private
		def backpack_params
			params.require(:backpack).permit(:model, :color, :capacity, :number_pockets, :waterproof, :price)
		end
end

Week2/ecommerce/app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
	def welcome
		@laptops
		@backpacks
	end
	def index
		@laptops = Laptop.all
	end
	def new
		@laptop = Laptop.new
	end
	def show
		@laptop = Laptop.find(params[:id])
	end
	def edit
		@laptop = Laptop.find(params[:id])
	end
	def create
		@laptop = Laptop.new(laptop_params)
		@laptop.save
		redirect_to laptop_path(@laptop)
	end
	def update
		@laptop = Laptop.find(params[:id])
		@laptop.update(laptop_params)
		redirect_to laptop_path(@laptop)
	end
	def destroy
		@laptop = Laptop.find(params[:id])
		@laptop.destroy
		redirect_to laptops_path
	end
	private
		def laptop_params
			params.require(:laptop).permit(:brand, :model, :processor_brand, :ram_size, :price)
		end
end

Week2/ecommerce/app/helpers/application_helper.rb
module ApplicationHelper
end

Week2/ecommerce/app/helpers/backpacks_helper.rb
module BackpacksHelper
end

Week2/ecommerce/app/helpers/laptops_helper.rb
module LaptopsHelper
end

Week2/ecommerce/app/views/backpacks/edit.html.erb
<h1> Editing backpack </h1>
<%= form_for :backpack, url: backpack_path(@backpack), method: :patch do |f| %>
	<p>
		<%= f.label :model %><br>
		<%= f.text_field :model %>
	</p>
	<p>
		<%= f.label :color %><br>
		<%= f.text_field :color %>
	</p>
	<p>
		<%= f.label :capacity %><br>
		<%= f.text_field :capacity %>
	</p>
	<p>
		<%= f.label :number_pockets %><br>
		<%= f.text_field :number_pockets %>
	</p>
	<p>
		<%= f.label :waterproof %><br>
		<%= f.text_field :waterproof %>
	</p>
	<p>
		<%= f.label :price %><br>
		<%= f.text_field :price %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>
<%= link_to "Backpacks page", backpacks_path %>

Week2/ecommerce/app/views/backpacks/index.html.erb
<h1>Listing Backpacks</h1>
	<% @backpacks.each do |backpack| %>
	<div><%= backpack.model %> <%= link_to "Show Backpack", backpack_path(backpack) %>
		<%= link_to "Edit Backpack", edit_backpack_path(backpack) %>
		<%= link_to "Delete Backpack", backpack_path(backpack), method: :delete, data: { confirm: "Are you sure?"} %>
	</div>
	<%end%>
<p>
	<%= link_to "New backpack", new_backpack_path %>
	<%= link_to "Welcome ecommerce", root_path %>
</p>

Week2/ecommerce/app/views/backpacks/new.html.erb
<%= form_for @backpack do |f| %>
	<p>
		<%= f.label :model %><br>
		<%= f.text_field :model %>
	</p>
	<p>
		<%= f.label :color %><br>
		<%= f.text_field :color %>
	</p>
	<p>
		<%= f.label :capacity %><br>
		<%= f.text_field :capacity %>
	</p>
	<p>
		<%= f.label :number_pockets %><br>
		<%= f.text_field :number_pockets %>
	</p>
	<p>
		<%= f.label :waterproof %><br>
		<%= f.text_field :waterproof %>
	</p>
	<p>
		<%= f.label :price %><br>
		<%= f.text_field :price %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>
<%= link_to "Backpacks page", backpacks_path %>

Week2/ecommerce/app/views/backpacks/show.html.erb
<h3>
	<strong> Model: </strong>
	<%= @backpack.model %>
</h3>
<p>
	<strong> Color: </strong>
	<%= @backpack.color %>
</p>
<p>
	<strong> Capacity (liters): </strong>
	<%= @backpack.capacity %>
</p>
<p>
	<strong> Number of pockets: </strong>
	<%= @backpack.number_pockets %>
</p>
<p>
	<strong> Is it waterproof?: </strong>
	<%= @backpack.waterproof %>
</p>
<p>
	<strong> Price: </strong>
	<%= @backpack.price %>
</p>
<%= link_to "Edit backpack", edit_backpack_path(@backpack) %>
<%= link_to "Backpack page", backpacks_path %>

Week2/ecommerce/app/views/laptops/edit.html.erb
<h1> Editing laptop </h1>
<%= form_for :laptop, url: laptop_path(@laptop), method: :patch do |f| %>
	<p>
		<%= f.label :brand %><br>
		<%= f.text_field :brand %>
	</p>
	<p>
		<%= f.label :model %><br>
		<%= f.text_area :model %>
	</p>
	<p>
		<%= f.label :processor_brand %><br>
		<%= f.text_field :processor_brand %>
	</p>
	<p>
		<%= f.label :ram_size %><br>
		<%= f.text_field :ram_size %>
	</p>
	<p>
		<%= f.label :price %><br>
		<%= f.text_field :price %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>
<%= link_to "Laptops page", laptops_path %>

Week2/ecommerce/app/views/laptops/index.html.erb
<h1>Listing Laptops</h1>
	<% @laptops.each do |laptop| %>
	<div><%= laptop.brand %> <%= laptop.model %> <%= link_to "Show laptop", laptop_path(laptop) %>
		<%= link_to "Edit laptop", edit_laptop_path(laptop) %>
		<%= link_to "Delete laptop", laptop_path(laptop), method: :delete, data: { confirm: "Are you sure?"} %>
	</div>
	<%end%>
<p>
	<%= link_to "New laptop", new_laptop_path %>
	<%= link_to "Welcome ecommerce", root_path %>
</p>

Week2/ecommerce/app/views/laptops/new.html.erb
<%= form_for @laptop do |f| %>
	<p>
		<%= f.label :brand %><br>
		<%= f.text_field :brand %>
	</p>
	<p>
		<%= f.label :model %><br>
		<%= f.text_area :model %>
	</p>
	<p>
		<%= f.label :processor_brand %><br>
		<%= f.text_field :processor_brand %>
	</p>
	<p>
		<%= f.label :ram_size %><br>
		<%= f.text_field :ram_size %>
	</p>
	<p>
		<%= f.label :price %><br>
		<%= f.text_field :price %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>
<%= link_to "Laptops page", laptops_path %>

Week2/ecommerce/app/views/laptops/show.html.erb
<h3>
	<strong> Brand: </strong>
	<%= @laptop.brand %>
</h3>
<p>
	<strong> Model: </strong>
	<%= @laptop.model %>
</p>
<p>
	<strong> Processor brand: </strong>
	<%= @laptop.processor_brand %>
</p>
<p>
	<strong> RAM size: </strong>
	<%= @laptop.ram_size %>
</p>
<p>
	<strong> Price: </strong>
	<%= @laptop.price %>
</p>
<%= link_to "Edit laptop", edit_laptop_path(@laptop) %>
<%= link_to "Laptops page", laptops_path %>

Week2/ecommerce/app/views/laptops/welcome.html.erb
<h1> Our items! </h1>
<%= link_to "Laptops", laptops_path %>
<%= link_to "Backpacks", backpacks_path %>

Week2/ecommerce/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>